module.exports = {
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // ── UI backgrounds ──────────────────────────────────────────
        background: 'var(--color-background)',
        'background-dark': 'var(--color-background-dark)',
        'grouped-background': 'var(--color-grouped-background)',
        'grouped-background-dark': 'var(--color-grouped-background-dark)',
        surface: 'var(--color-surface)',
        'surface-dark': 'var(--color-surface-dark)',
        sheet: 'var(--color-sheet)',
        'sheet-dark': 'var(--color-sheet-dark)',
        // ── Text ────────────────────────────────────────────────────
        label: 'var(--color-label)',
        'label-dark': 'var(--color-label-dark)',
        'secondary-label': 'var(--color-secondary-label)',
        'secondary-label-dark': 'var(--color-secondary-label-dark)',
        'tertiary-label': 'var(--color-tertiary-label)',
        'tertiary-label-dark': 'var(--color-tertiary-label-dark)',
        'label-on-tint': 'var(--color-label-on-tint)',
        'label-on-tint-dark': 'var(--color-label-on-tint-dark)',
        // ── Decorative ──────────────────────────────────────────────
        separator: 'var(--color-separator)',
        'separator-dark': 'var(--color-separator-dark)',
        tint: 'var(--color-tint)',
        'tint-dark': 'var(--color-tint-dark)',
        destructive: 'var(--color-destructive)',
        'destructive-dark': 'var(--color-destructive-dark)',
        // ── Inputs ──────────────────────────────────────────────────
        'field-background': 'var(--color-field-background)',
        'field-background-dark': 'var(--color-field-background-dark)',
        'field-border': 'var(--color-field-border)',
        'field-border-dark': 'var(--color-field-border-dark)',
        placeholder: 'var(--color-placeholder)',
        'placeholder-dark': 'var(--color-placeholder-dark)',
        // ── Sheet indicator ─────────────────────────────────────────
        'handle-indicator': 'var(--color-handle-indicator)',
        'handle-indicator-dark': 'var(--color-handle-indicator-dark)',
        // ── Other ───────────────────────────────────────────────────
        error: 'var(--color-error)',
        'error-dark': 'var(--color-error-dark)',
        // ── Map ─────────────────────────────────────────────────────
        pin: 'var(--color-pin)',
        'pin-dark': 'var(--color-pin-dark)',
        'pin-stroke': 'var(--color-pin-stroke)',
        'pin-stroke-dark': 'var(--color-pin-stroke-dark)',
        // ── Price badges ───────────────────────────────────────────
        'price-low': 'var(--color-price-low)',
        'price-low-dark': 'var(--color-price-low-dark)',
        'price-low-tint': 'var(--color-price-low-tint)',
        'price-low-tint-dark': 'var(--color-price-low-tint-dark)',
        'price-mid': 'var(--color-price-mid)',
        'price-mid-dark': 'var(--color-price-mid-dark)',
        'price-high': 'var(--color-price-high)',
        'price-high-dark': 'var(--color-price-high-dark)',
        'price-high-tint': 'var(--color-price-high-tint)',
        'price-high-tint-dark': 'var(--color-price-high-tint-dark)',
        // ── Worth the drive ─────────────────────────────────────────
        'worth-it-text': 'var(--color-worth-it-text)',
        'worth-it-text-dark': 'var(--color-worth-it-text-dark)',
        'worth-it-bg': 'var(--color-worth-it-bg)',
        'worth-it-bg-dark': 'var(--color-worth-it-bg-dark)',
        'not-worth-text': 'var(--color-not-worth-text)',
        'not-worth-text-dark': 'var(--color-not-worth-text-dark)',
        'not-worth-bg': 'var(--color-not-worth-bg)',
        'not-worth-bg-dark': 'var(--color-not-worth-bg-dark)',
        // ── Favorite ───────────────────────────────────────────────
        favorite: 'var(--color-favorite)',
        'favorite-dark': 'var(--color-favorite-dark)',
        // ── Charts ─────────────────────────────────────────────────
        'chart-line': 'var(--color-chart-line)',
        'chart-line-dark': 'var(--color-chart-line-dark)',
        'chart-grid': 'var(--color-chart-grid)',
        'chart-grid-dark': 'var(--color-chart-grid-dark)',
        'chart-label': 'var(--color-chart-label)',
        'chart-label-dark': 'var(--color-chart-label-dark)',
        'chart-dot': 'var(--color-chart-dot)',
        'chart-dot-dark': 'var(--color-chart-dot-dark)',
        // ── Radar ──────────────────────────────────────────────────
        'radar-line': 'var(--color-radar-line)',
        'radar-line-dark': 'var(--color-radar-line-dark)',
        'radar-dot': 'var(--color-radar-dot)',
        'radar-dot-dark': 'var(--color-radar-dot-dark)',
        'radar-best': 'var(--color-radar-best)',
        'radar-best-dark': 'var(--color-radar-best-dark)',
        'radar-grid': 'var(--color-radar-grid)',
        'radar-grid-dark': 'var(--color-radar-grid-dark)',
        'radar-label': 'var(--color-radar-label)',
        'radar-label-dark': 'var(--color-radar-label-dark)',
        // ── Day banner ─────────────────────────────────────────────
        'day-banner-bg': 'var(--color-day-banner-bg)',
        'day-banner-bg-dark': 'var(--color-day-banner-bg-dark)',
        'day-banner-text': 'var(--color-day-banner-text)',
        'day-banner-text-dark': 'var(--color-day-banner-text-dark)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '24px',
        xxxl: '32px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
      },
      fontSize: {
        'large-title': ['34px', { fontWeight: 'bold' }],
        'title-1': ['28px', { fontWeight: 'bold' }],
        'title-2': ['22px', { fontWeight: 'bold' }],
        'title-3': ['20px', { fontWeight: '600' }],
        headline: ['17px', { fontWeight: '600' }],
        body: ['17px', { fontWeight: '400' }],
        callout: ['17px', { fontWeight: '400' }],
        subheadline: ['16px', { fontWeight: '400' }],
        footnote: ['14px', { fontWeight: '400' }],
        'caption-1': ['12px', { lineHeight: '14px', fontWeight: '400' }],
        'caption-2': ['11px', { fontWeight: '400' }],
      },
    },
  },
};