module.exports = {
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        'background-dark': 'var(--color-background-dark)',
        'grouped-background': 'var(--color-grouped-background)',
        'grouped-background-dark': 'var(--color-grouped-background-dark)',
        surface: 'var(--color-surface)',
        'surface-dark': 'var(--color-surface-dark)',
        label: 'var(--color-label)',
        'label-dark': 'var(--color-label-dark)',
        'secondary-label': 'var(--color-secondary-label)',
        'secondary-label-dark': 'var(--color-secondary-label-dark)',
        'tertiary-label': 'var(--color-tertiary-label)',
        'tertiary-label-dark': 'var(--color-tertiary-label-dark)',
        separator: 'var(--color-separator)',
        'separator-dark': 'var(--color-separator-dark)',
        tint: 'var(--color-tint)',
        'tint-dark': 'var(--color-tint-dark)',
        'price-low': 'var(--color-price-low)',
        'price-low-dark': 'var(--color-price-low-dark)',
        'price-low-tint': 'var(--color-price-low-tint)',
        'price-low-tint-dark': 'var(--color-price-low-tint-dark)',
        'price-mid': 'var(--color-price-mid)',
        'price-mid-dark': 'var(--color-price-mid-dark)',
        'price-high': 'var(--color-price-high)',
        'price-high-dark': 'var(--color-price-high-dark)',
        'price-high-tint': 'var(--color-price-high-tint)',
        'price-high-tint-dark': 'var(--color-price-high-tint-dark)',
        destructive: 'var(--color-destructive)',
        'destructive-dark': 'var(--color-destructive-dark)',
        'field-background': 'var(--color-field-background)',
        'field-background-dark': 'var(--color-field-background-dark)',
        'field-border': 'var(--color-field-border)',
        'field-border-dark': 'var(--color-field-border-dark)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '24px',
        xxxl: '32px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
      },
      fontSize: {
        'large-title': ['34px', { fontWeight: 'bold' }],
        'title-1': ['28px', { fontWeight: 'bold' }],
        'title-2': ['22px', { fontWeight: 'bold' }],
        'title-3': ['20px', { fontWeight: '600' }],
        headline: ['17px', { fontWeight: '600' }],
        body: ['17px', { fontWeight: '400' }],
        callout: ['17px', { fontWeight: '400' }],
        subheadline: ['16px', { fontWeight: '400' }],
        footnote: ['14px', { fontWeight: '400' }],
        'caption-1': ['12px', { lineHeight: '14px', fontWeight: '400' }],
        'caption-2': ['11px', { fontWeight: '400' }],
      },
    },
  },
};
