module.exports = {
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#FFFFFF',
        'background-dark': '#000000',
        'grouped-background': '#F2F2F7',
        'grouped-background-dark': '#000000',
        surface: '#FFFFFF',
        'surface-dark': '#1C1C1E',
        label: '#000000',
        'label-dark': '#FFFFFF',
        'secondary-label': 'rgba(60, 60, 67, 0.6)',
        'secondary-label-dark': 'rgba(235, 235, 245, 0.6)',
        'tertiary-label': 'rgba(60, 60, 67, 0.3)',
        'tertiary-label-dark': 'rgba(235, 235, 245, 0.3)',
        separator: 'rgba(60, 60, 67, 0.21)',
        'separator-dark': 'rgba(84, 84, 88, 0.6)',
        tint: '#0C8599',
        'tint-dark': '#22B8CD',
        'price-low': '#22A559',
        'price-low-dark': '#30D158',
        'price-mid': '#F2A93B',
        'price-mid-dark': '#FFD60A',
        'price-high': '#E5484D',
        'price-high-dark': '#FF453A',
        destructive: '#FF3B30',
        'destructive-dark': '#FF453A',
        'field-background': '#FFFFFF',
        'field-background-dark': '#1C1C1E',
        'field-border': 'rgba(60, 60, 67, 0.21)',
        'field-border-dark': 'rgba(84, 84, 88, 0.6)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '24px',
        xxxl: '32px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
      },
      fontSize: {
        'large-title': ['34px', { fontWeight: 'bold' }],
        'title-1': ['28px', { fontWeight: 'bold' }],
        'title-2': ['22px', { fontWeight: 'bold' }],
        'title-3': ['20px', { fontWeight: '600' }],
        headline: ['17px', { fontWeight: '600' }],
        body: ['17px', { fontWeight: '400' }],
        callout: ['16px', { fontWeight: '400' }],
        subheadline: ['15px', { fontWeight: '400' }],
        footnote: ['13px', { fontWeight: '400' }],
        'caption-1': ['12px', { lineHeight: '14px', fontWeight: '400' }],
        'caption-2': ['11px', { fontWeight: '400' }],
      },
    },
  },
};
